---
title: My personal blog - Nadin Vorontsova
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
permalink: ":title/"
url: ''
author: Nadya Vorontsova
author-pic: avatar.jpg
about-author: My name is Nadezhda and I am krasotka.
phone: 
website: 
instagram: 
discus_identifier: 
analytics: 
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
