---
title: My personal blog - Nadya Vorontsova
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nadin.countess@gmail.com
description: Меня зовут Надя Воронцова. Здесь я пишу о путешествиях и о своих увлечениях.
permalink: ":title/"
url: http://raven-and-owl.ru
author: Nadya Vorontsova
author-pic: avatar.jpg
about-author: Меня зовут Надя Воронцова. Здесь я пишу о путешествиях и о своих увлечениях.
phone: 
website: 
instagram: nadya_vorontsova
vk: nadin_countess
discus_identifier: nadin-vorontsova-github-com
analytics: 
yandex-metrika: 47839994
paginate: 12
paginate_path: "/page:num/"
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jemoji
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
