---
title: Дневники путешественника
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nadin.countess@gmail.com
description: Меня зовут Надя Воронцова. Здесь я пишу о путешествиях и о своих увлечениях.
permalink: ":title/"
url: http://raven-and-owl.ru
author: Nadya Vorontsova
author-pic: avatar.jpg
about-author: Меня зовут Надя Воронцова. Здесь я пишу о путешествиях и о своих увлечениях.
phone: 
website: 
instagram: nadya_vorontsova
vk: nadin_countess
discus_identifier: nadin-vorontsova-github-com
analytics: 
yandex-metrika: 47839994
paginate: 20
paginate_path: "/page:num/"
markdown: kramdown
instagram_user_id: 46429618
instagram_client_id: 375fb1518e8a46adaa1297a1647c82a0
instagram_access_token: 46429618.375fb15.5775661ad099493fb283bfd293ad8ab4
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jemoji
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
