---
title: My personal blog - Nadin Vorontsova
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nadin.countess@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
permalink: ":title/"
url: ''
author: Nadya Vorontsova
author-pic: avatar.jpg
about-author: Меня зовут Надя Воронцова. Здесь я пишу о путешествиях и о своих увлечениях.
phone: 
website: 
instagram: nadya_vorontsova
vk: nadin_countess
discus_identifier: nadyavorontsova
analytics: 
yandex-metrika: 47839994
paginate: 6
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jemoji
include:
- _pages
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
